### PR TITLE
Fiat units patch

### PR DESCRIPTION
**Pull request by nolim1t**
placeholder for fiat units

### CODE REVIEW

**Comment by mayankchhabra** [comment]
ACK the need too support multiple currencies. You have a good approach, and we need a way for the user to change the preferred currency in the dashboard. 

- So first we'd need an option on `/settings` page with a dropdown to change the currencies. 
- Then we need to store the preferred currency in the `db/user.json` file (which is loaded on the first load) because the current implementation will reset the currency back to USD (or whichever we choose as default) on every load.

**Comment by nolim1t** [comment]
This is just the infrastructure for it.. obviously would have to change the backend too for it to work end to end.

**Comment by nolim1t** [comment]
Some samples on testnet

samples

**Comment by mayankchhabra** [comment]
Looking good, it'd be worthwhile to implement this via the `system` store module instead of the `bitcoin` store module, as essentially it's a system setting/preference set by the user: https://github.com/getumbrel/umbrel-dashboard/blob/master/src/store/modules/system.js

**Comment by nolim1t** [comment]
The reason why its under bitcoin store is its where the price data is.

Also renamed some vue filters too in this PR

**Comment by nolim1t** [comment]
Backend task

https://github.com/getumbrel/umbrel-manager/issues/9

**Comment by mayankchhabra** [comment]
Yeah, let's move the price data to the system store module, and also club it with #62 

So we can do a new manager endpoint `POST /v1/account/preferences` that saves and updates preferences in `user.json`. 

Examples:

1. To change preferred currency
```
POST /v1/account/preferences
{
    "currency": "THB"
}
```

2. To switch between sats/btc
```
POST /v1/account/preferences

{
    "unit": "sats"
}
```

3. Update multiple preferences at one time:
```
POST /v1/account/preferences

{
    "currency": "THB"
    "unit": "sats"
}
```

Eg of updated `db/user.json`:

```
{
    name: "Satoshi"
    password: "hsvdy78d7fydfjdkfdf"
    seed: "shd789768239bcsd"
    unit: "sats"
    currency: "THB"
}

Later it'd be easy to implement more system settings, eg storing dark/light mode preference, etc.

Also `GET /v1/account/info` already returns user.json (except hashed password and encrypted seed) on the first load so we don't need to implement a separate way to retrieve user preferences in the dashboard.

**Comment by nolim1t** [comment]
> Yeah, let's move the price data to the system store module, and also club it with #62

Like this?

https://github.com/getumbrel/umbrel-dashboard/pull/103/commits/300ad267829a7191d9808b13529b0883e4693236

**Comment by mayankchhabra** [comment]
LGTM

**Comment by nolim1t** [comment]
> LGTM

only that it doesn't seem to work when I put it into the Vue.filter

**Comment by nolim1t** [comment]
Ok all moved across to system store.

**Comment by nolim1t** [comment]
I've called the key ```stateCurrencyPreference``` (to accurately describe internally what it is) which can be added to user.json manually (if it doesn't exist it will default to USD).

**Comment by nolim1t** [comment]
We will need an API for the preferences eventually, as there are some weird cache issues.

**Comment by nolim1t** [comment]
Tested for backwards compatibility and without. 

Would appreciate some tests for this too

**Pull request closed without merging**
