### PR TITLE
Change default block explorer from blockstream.info to mempool.space

### PR DESCRIPTION
**Pull request by wiz**

### CODE REVIEW

**Comment by AaronDewes** [comment]
Why should this change happen? You had no reason for this change in the description, so I'm curious to know the reason.

**Comment by lukechilds** [comment]
@AaronDewes @wiz is part of the mempool.space team, he was discussing this with me on Twitter beforehand, I asked him to  open the PR lol.

I think mempool.space is probably a better default for Umbrel. I love blockstream.info personally but it's a little more hardcore and exposes things like scripthashes and other developer stuff. I think mempool.space is probably less confusing for our users.

Also @wiz is interested in packaging mempool.space for Umbrel once we have apps implemented. So it would be quite cool if users get linked to the hosted mempool.space by default when clicking a transaction, but if they install the mempool.space app they get the same UI as before but now it's self hosted!

**Comment by wiz** [comment]
@AaronDewes hey Aaron, yeah we're going to package up mempool into an app to be part of the umbrel system so the goal is to have it self-hosted 😁

**Review by mayankchhabra — APPROVED** [review]
Sweet! Thanks, @wiz. Can't wait for the self-hosted mempool.space!

**Pull request merged**
